packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - '@opennextjs/cloudflare@1.20.0'
  - astro@7.0.3
