import type { Metadata } from 'next';
import Link from 'next/link';

import { JsonLd } from '@/components/json-ld';
import { site } from '@/lib/site';

export const metadata: Metadata = {
  title: 'Usage Rights',
  description:
    'All Pāli texts and AI-generated translations on Tipiṭaka Online are dedicated to the public domain under CC0. Free for any use, including AI training.',
};

const PERMISSIONS = [
  'Copy, reproduce, and distribute all content freely.',
  'Adapt or build upon the texts and translations.',
  'Use commercially, non-commercially, or for academic research.',
  'Train large language models or other AI systems on the content.',
  'No attribution required — though it is appreciated.',
];

export default function UsageRightsPage() {
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    name: 'Usage Rights — Tipiṭaka Online',
    url: `${site.url}/usage-rights`,
    description: metadata.description,
    license: site.license,
    isAccessibleForFree: true,
  };

  return (
    <main className="mx-auto w-full max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
      <JsonLd data={jsonLd} />
      <header>
        <h1 className="font-reading text-4xl font-semibold tracking-tight">
          Usage Rights
        </h1>
        <p className="mt-3 text-lg text-muted-foreground">
          Everything on this site is free to use, adapt, and redistribute — for
          any purpose, including AI training.
        </p>
      </header>

      <section className="mt-10 space-y-6">
        <div className="rounded-xl border border-border bg-card p-6">
          <h2 className="text-xl font-semibold">
            Creative Commons Zero (CC0 1.0 Universal)
          </h2>
          <p className="mt-2 text-muted-foreground">
            All canonical Pāli texts and AI-generated translations on this site
            are dedicated to the <strong>public domain</strong> under the{' '}
            <a
              href={site.license}
              target="_blank"
              rel="noopener noreferrer"
              className="font-medium text-foreground hover:underline"
            >
              Creative Commons Zero (CC0 1.0) Public Domain Dedication
            </a>
            . No permission or attribution is required.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold">What this means</h2>
          <ul className="mt-3 space-y-2 text-muted-foreground">
            {PERMISSIONS.map((item) => (
              <li key={item} className="flex gap-2">
                <span className="mt-0.5 text-foreground">✓</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>

        <div>
          <h2 className="text-lg font-semibold">Source texts</h2>
          <p className="mt-2 text-muted-foreground">
            The canonical Pāli texts are from the{' '}
            <strong>Chaṭṭha Saṅgāyana Tipiṭaka (CST)</strong>, digitized by the
            Vipassana Research Institute (VRI). The original Pāli text has been
            in the public domain for over two millennia.
          </p>
          <p className="mt-2 text-muted-foreground">
            Translations on this site are generated by AI and have not been
            reviewed by human scholars. They are provided for study and
            reference; consult authoritative human translations for critical
            scholarship.
          </p>
        </div>

        <div className="rounded-xl border border-border bg-muted/30 p-5 text-sm text-muted-foreground">
          <p>
            Questions about usage?{' '}
            <Link
              href={site.paths.developers}
              className="font-medium text-foreground hover:underline"
            >
              See the developer page
            </Link>{' '}
            for API access and bulk data export.
          </p>
        </div>
      </section>
    </main>
  );
}
