import type { Metadata } from 'next';
import Link from 'next/link';

import {
  Card,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Pali } from '@/components/reader/pali';
import { JsonLd } from '@/components/json-ld';
import { site } from '@/lib/site';

export const metadata: Metadata = {
  title: 'About the Tipiṭaka',
  description:
    'What the Tipiṭaka is, which edition this site serves (Chaṭṭha Saṅgāyana / CST), the three baskets, and how the Pāli Canon was preserved — from oral tradition through the councils to writing.',
};

const BASKETS = [
  {
    title: 'Vinaya Piṭaka',
    pali: 'Vinayapiṭaka',
    body: 'The basket of discipline — the rules of monastic life, together with the stories that explain how each rule came to be laid down.',
  },
  {
    title: 'Sutta Piṭaka',
    pali: 'Suttapiṭaka',
    body: 'The basket of discourses — the teachings of the Buddha and his disciples, gathered into five Nikāyas, from long discourses to short verses.',
  },
  {
    title: 'Abhidhamma Piṭaka',
    pali: 'Abhidhammapiṭaka',
    body: 'The basket of higher doctrine — a systematic, analytical treatment of mind, matter, and the processes of experience.',
  },
];

const TIMELINE = [
  {
    label: 'Oral tradition',
    body: 'The teachings were memorized and recited communally by monastics, preserved through structured group recitation.',
  },
  {
    label: 'The councils',
    body: 'A series of councils (saṅgāyana) gathered the community to recite, agree, and standardize the texts.',
  },
  {
    label: 'Written down',
    body: 'Around the 1st century BCE in Sri Lanka, the canon was committed to writing on palm leaves.',
  },
  {
    label: 'Sixth Council (CST)',
    body: 'In 1954–1956 the Sixth Buddhist Council (Chaṭṭha Saṅgāyana) in Rangoon reviewed, standardized, and published the edition served on this site — the Chaṭṭha Saṅgāyana Tipiṭaka (CST).',
  },
];

const faqJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  '@id': `${site.url}/about`,
  name: 'About the Tipiṭaka — FAQ',
  mainEntity: [
    {
      '@type': 'Question',
      name: 'What is the Tipiṭaka (Pāli Canon)?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'The Tipiṭaka is the complete collection of canonical Buddhist scriptures in the Pāli language. "Tipiṭaka" means "three baskets": the Vinaya Piṭaka (monastic discipline), the Sutta Piṭaka (discourses of the Buddha), and the Abhidhamma Piṭaka (systematic philosophy).',
      },
    },
    {
      '@type': 'Question',
      name: 'Which edition is on this site?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'This site serves the Chaṭṭha Saṅgāyana Tipiṭaka (CST) — the Sixth Council edition standardized in Rangoon, Burma, between 1954 and 1956, and digitized by the Vipassana Research Institute (VRI).',
      },
    },
    {
      '@type': 'Question',
      name: 'Are the translations human or AI-generated?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Translations on this site are generated by AI and rendered live in the browser. They have not been reviewed by human scholars. The canonical Pāli text itself is unmodified from the CST edition.',
      },
    },
    {
      '@type': 'Question',
      name: 'Can I use these texts freely?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Yes. All content is dedicated to the public domain under Creative Commons Zero (CC0). You may use, copy, adapt, or build upon the texts and translations for any purpose, including AI training, with no attribution required.',
      },
    },
    {
      '@type': 'Question',
      name: 'What scripts and languages are available?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'The Pāli text is served in Roman/IAST script (the international scholarly standard) and can be transliterated live in the browser into 18 scripts including Sinhala, Devanagari, Thai, Myanmar, Khmer, Tibetan, and more. AI-generated translations into English, Sinhala, Thai, and Burmese are available for study.',
      },
    },
  ],
};

export default function AboutPage() {
  return (
    <main className="mx-auto w-full max-w-[1400px] px-4 py-12 sm:px-6 lg:px-8">
      <JsonLd data={faqJsonLd} />
      <header className="max-w-4xl">
        <h1 className="font-reading text-4xl font-semibold tracking-tight">
          About the Tipiṭaka
        </h1>
        <p className="mt-3 text-lg text-muted-foreground">
          &ldquo;Tipiṭaka&rdquo; means <em>three baskets</em> — the collection
          of texts that make up the Pāli Canon, the earliest complete corpus of
          Buddhist scripture. This site serves the{' '}
          <strong>Chaṭṭha Saṅgāyana Tipiṭaka (CST)</strong>, the Burmese Sixth
          Council edition standardized in Rangoon in 1954&ndash;1956.
        </p>
      </header>

      <section className="mt-10">
        <h2 className="text-2xl font-semibold tracking-tight">
          The three baskets
        </h2>
        <div className="mt-4 grid gap-3 md:grid-cols-3">
          {BASKETS.map((b) => (
            <Card key={b.title}>
              <CardHeader>
                <CardTitle className="font-reading text-lg">
                  {b.title}{' '}
                  <span className="text-muted-foreground">
                    · <Pali text={b.pali} />
                  </span>
                </CardTitle>
                <CardDescription>{b.body}</CardDescription>
              </CardHeader>
            </Card>
          ))}
        </div>
      </section>

      <section className="mt-10">
        <h2 className="text-2xl font-semibold tracking-tight">
          How it was preserved
        </h2>
        <ol className="mt-4 grid gap-4 md:grid-cols-3">
          {TIMELINE.map((t, i) => (
            <li
              key={t.label}
              className="rounded-xl border border-border bg-card p-5"
            >
              <span className="mb-3 grid size-7 place-items-center rounded-full border border-border bg-background text-xs font-medium">
                {i + 1}
              </span>
              <h3 className="font-medium">{t.label}</h3>
              <p className="text-muted-foreground">{t.body}</p>
            </li>
          ))}
        </ol>
        <p className="mt-6 text-sm text-muted-foreground">
          This is placeholder introductory text for UI development — the full
          guide is written later.
        </p>
      </section>

      <section className="mt-10 rounded-xl border border-border bg-muted/30 p-6">
        <h2 className="text-lg font-medium">Start reading</h2>
        <p className="mt-1 text-sm text-muted-foreground">
          Browse the hierarchy, or look up a recurring term in the glossary.
        </p>
        <div className="mt-4 flex flex-wrap gap-3">
          <Button nativeButton={false} render={<Link href="/sutta" />}>
            Browse the Sutta Piṭaka
          </Button>
          <Button
            variant="outline"
            nativeButton={false}
            render={<Link href="/glossary" />}
          >
            Open the glossary
          </Button>
        </div>
      </section>
    </main>
  );
}
